### ISSUE TITLE
Error: Ubuntu version 22.04 is not supported!

### ISSUE THREAD

**Issue by shenki** [ghdl/setup-ghdl-ci#33]
Thanks for merging my patch for 22.02 support. When I attempt to use it I get this:

> Error: Ubuntu version 22.04 is not supported!

Do we need a new tag?

```
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checkout Repository
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CCache
        uses: hendrikmuhs/ccache-action@v1.2

      - uses: ghdl/setup-ghdl-ci@nightly
        with:
          backend: llvm
```
