### ISSUE TITLE
Nightly path broken

### ISSUE THREAD

**Issue by LarsAsplund** [ghdl/setup-ghdl-ci#44]
Looks like the path to the nightly builds have changed with the latest release such that this action fails. This [line](https://github.com/ghdl/setup-ghdl-ci/blob/2f5b463df26c476725ef2cafb9e39bea7e9e30d3/main.js#L42) seems to be the problem. It assumes that the path ends with `ci-1-any.pkg.tar.zst` but the latest release ends with `5.0.0.dev-1-any.pkg.tar.zst`

**Comment by Paebbels** [comment]
> [!CAUTION]
> This GitHub Action (`setup-ghdl-ci`) has been **deprecated** in favor of the new [setup-ghdl](https://github.com/ghdl/setup-ghdl) Action.
> Please update your YAML files and transition to the new GitHub Action. See the linked repository for details on optional parameters.

**Quick example:**
```yml
jobs:
  GHDL-on-Ubuntu:
    runs-on: ubuntu-24.04
    steps:
      - name: Run VHDL Simulation
        uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: mcode
```

**Why has it been changed?**  
* The Javascript GitHub Action is hard to maintain.  
  In addition, it has a high complexity with Node.js and other tools compare to a much simpler Composite Action using simple shell instructions in Bash/Powershell.
* This action doesn't support the `ubuntu-24.04` (= `ubuntu-latest`) runner image.
* This Action uses wrong tagging to select GHDL versions. See analysis: https://github.com/ghdl/ghdl/issues/2852
* Due to changes in GHDL's nightly releases and attached assets, the filenames are broken.
